name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

  push:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ias_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ENV: test
      DEBUG: false
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ias_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run tests
        run: pytest

      - name: Run Bandit
        run: bandit -r app

  deploy-dev:
    if: github.ref == 'refs/heads/develop'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DEV
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_DEV }}"

  deploy-qa:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to QA
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_QA }}"

  deploy-prd:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to PRD
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_PRD }}"